api:
  dashboard: true
  insecure: true
 
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

http:
  routers:
    api:
      rule: "Host(`api.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
        - "websecure"
      service: "api"
      tls: true
 
    pwa:
      rule: "Host(`pwa.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
        - "websecure"
      service: "pwa"
      tls: true
 
    manage:
      rule: "Host(`manage.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
        - "websecure"
      service: "manage"
      tls: true
 
    control:
      rule: "Host(`control.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
        - "websecure"
      service: "control"
      tls: true
 
    auth:
      rule: "Host(`auth.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
        - "websecure"
      service: "auth"
      tls: true
 
    func-responses:
      rule: "Host(`func-responses.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
        - "websecure"
      service: "func-responses"
      tls: true
 
    func-response-processor:
      rule: "Host(`func-response-processor.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
        - "websecure"
      service: "func-response-processor"
      tls: true
 
  services:
    api:
      loadBalancer:
        servers:
          - url: "http://host.containers.internal:3000"
 
    pwa:
      loadBalancer:
        servers:
          - url: "http://host.containers.internal:3001"
 
    manage:
      loadBalancer:
        servers:
          - url: "http://host.containers.internal:3002"
 
    control:
      loadBalancer:
        servers:
          - url: "http://host.containers.internal:3003"
 
    auth:
      loadBalancer:
        servers:
          - url: "http://host.containers.internal:3010"
 
    func-responses:
      loadBalancer:
        servers:
          - url: "http://host.containers.internal:7072"
 
    func-response-processor:
      loadBalancer:
        servers:
          - url: "http://host.containers.internal:7073"