http:
  routers:
    api:
      rule: "Host(`api.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
      service: "api"

    pwa:
      rule: "Host(`pwa.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
      service: "pwa"

    manage:
      rule: "Host(`manage.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
      service: "manage"

    control:
      rule: "Host(`control.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
      service: "control"

    auth:
      rule: "Host(`auth.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
      service: "auth"

    func-responses:
      rule: "Host(`func-responses.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
      service: "func-responses"

    func-response-processor:
      rule: "Host(`func-response-processor.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
      service: "func-response-processor"

  services:
    api:
      loadBalancer:
        servers:
          - url: "http://api.klicker.xeno-isenegger.ch:3000"

    pwa:
      loadBalancer:
        servers:
          - url: "http://pwa.klicker.xeno-isenegger.ch:3001"

    manage:
      loadBalancer:
        servers:
          - url: "http://manage.klicker.xeno-isenegger.ch:3002"

    control:
      loadBalancer:
        servers:
          - url: "http://control.klicker.xeno-isenegger.ch:3003"

    auth:
      loadBalancer:
        servers:
          - url: "http://auth.klicker.xeno-isenegger.ch:3010"

    func-responses:
      loadBalancer:
        servers:
          - url: "http://func-response.klicker.xeno-isenegger.ch:7072"

    func-response-processor:
      loadBalancer:
        servers:
          - url: "http://func-response-processor.klicker.xeno-isenegger.ch:7073"
