# rules.toml
 
[http.routers]
  [http.routers.api]
    rule = "Host(`api.klicker.xeno-isenegger.ch`)"
    entrypoints = ["web"]
    service = "api"
    [http.routers.api.tls]
      certResolver = "internal"
 
  [http.routers.pwa]
    rule = "Host(`pwa.klicker.xeno-isenegger.ch`)"
    entrypoints = ["web"]
    service = "pwa"
    [http.routers.pwa.tls]
      certResolver = "internal"
 
  [http.routers.manage]
    rule = "Host(`manage.klicker.xeno-isenegger.ch`)"
    entrypoints = ["web"]
    service = "manage"
    [http.routers.manage.tls]
      certResolver = "internal"
 
  [http.routers.control]
    rule = "Host(`control.klicker.xeno-isenegger.ch`)"
    entrypoints = ["web"]
    service = "control"
    [http.routers.control.tls]
      certResolver = "internal"
 
  [http.routers.auth]
    rule = "Host(`auth.klicker.xeno-isenegger.ch`)"
    entrypoints = ["web"]
    service = "auth"
    [http.routers.auth.tls]
      certResolver = "internal"
 
  [http.routers.func-responses]
    rule = "Host(`func-responses.klicker.xeno-isenegger.ch`)"
    entrypoints = ["web"]
    service = "func-responses"
    [http.routers.func-responses.tls]
      certResolver = "internal"
 
  [http.routers.func-response-processor]
    rule = "Host(`func-response-processor.klicker.xeno-isenegger.ch`)"
    entrypoints = ["web"]
    service = "func-response-processor"
    [http.routers.func-response-processor.tls]
      certResolver = "internal"
 
[http.services]
  [http.services.api.loadBalancer]
    [[http.services.api.loadBalancer.servers]]
      url = "http://host.containers.internal:3000"
 
  [http.services.pwa.loadBalancer]
    [[http.services.pwa.loadBalancer.servers]]
      url = "http://host.containers.internal:3001"
 
  [http.services.manage.loadBalancer]
    [[http.services.manage.loadBalancer.servers]]
      url = "http://host.containers.internal:3002"
 
  [http.services.control.loadBalancer]
    [[http.services.control.loadBalancer.servers]]
      url = "http://host.containers.internal:3003"
 
  [http.services.auth.loadBalancer]
    [[http.services.auth.loadBalancer.servers]]
      url = "http://host.containers.internal:3010"
 
  [http.services.func-responses.loadBalancer]
    [[http.services.func-responses.loadBalancer.servers]]
      url = "http://host.containers.internal:7072"
 
  [http.services.func-response-processor.loadBalancer]
    [[http.services.func-response-processor.loadBalancer.servers]]
      url = "http://host.containers.internal:7073"
