api:
  dashboard: true
  insecure: true

log:
  level: "DEBUG"
  filePath: "./log-file.log"
  format: json 

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: stefansim2000@gmail.com 
      storage: "acme.json"
      httpChallenge:
        entryPoint: "websecure"

http:
  routers:
    api:
      rule: "Host(`api.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
        - "websecure"
      service: "middleware"
      tls: 
        certResolver: "myresolver"

    middleware:
      rule: "Host(`middleware.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
        - "websecure"
      service: "middleware"
      tls:
        certResolver: "myresolver"
 
    pwa:
      rule: "Host(`pwa.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
        - "websecure"
      service: "pwa"
      tls: 
        certResolver: "myresolver"
 
    manage:
      rule: "Host(`manage.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
        - "websecure"
      service: "manage"
      tls: 
        certResolver: "myresolver"
 
    control:
      rule: "Host(`control.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
        - "websecure"
      service: "control"
      tls: true
 
    auth:
      rule: "Host(`auth.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
        - "websecure"
      service: "auth"
      tls: 
        certResolver: "myresolver"
 
    func-responses:
      rule: "Host(`func-responses.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
        - "websecure"
      service: "func-responses"
      tls: true
 
    func-response-processor:
      rule: "Host(`func-response-processor.klicker.xeno-isenegger.ch`)"
      entrypoints:
        - "web"
        - "websecure"
      service: "func-response-processor"
      tls: true
 
  services:
    api:
      loadBalancer:
        servers:
          - url: "http://localhost:3000"
 
    middleware:
      loadBalancer:
        servers:
          - url: "http://host.containers.internal:3333"

    pwa:
      loadBalancer:
        servers:
          - url: "http://host.containers.internal:3001"
 
    manage:
      loadBalancer:
        servers:
          - url: "http://host.containers.internal:3002"
 
    control:
      loadBalancer:
        servers:
          - url: "http://host.containers.internal:3003"
 
    auth:
      loadBalancer:
        servers:
          - url: "http://host.containers.internal:3010"
 
    func-responses:
      loadBalancer:
        servers:
          - url: "http://host.containers.internal:7072"
 
    func-response-processor:
      loadBalancer:
        servers:
          - url: "http://host.containers.internal:7073"
